// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3vPX8EPm6lfQDKlHYJP8Ds0QC3T2m-E4',
    appId: '1:900834578203:web:ad9710793e8c1792ebcdbe',
    messagingSenderId: '900834578203',
    projectId: 'iosnative-9791f',
    authDomain: 'iosnative-9791f.firebaseapp.com',
    storageBucket: 'iosnative-9791f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChpyEkCJoLJiAxcIDLgcssEPkUJ2CFjE4',
    appId: '1:900834578203:android:5e205a8590576072ebcdbe',
    messagingSenderId: '900834578203',
    projectId: 'iosnative-9791f',
    storageBucket: 'iosnative-9791f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWvdnocvi4zXY1wS5Wij9VI-sNkiCtY8',
    appId: '1:900834578203:ios:8fe750179dd1dc86ebcdbe',
    messagingSenderId: '900834578203',
    projectId: 'iosnative-9791f',
    storageBucket: 'iosnative-9791f.appspot.com',
    iosClientId: '900834578203-cnrscsfb48b2m279tfkhg3n9cmhoad1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVsNative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGWvdnocvi4zXY1wS5Wij9VI-sNkiCtY8',
    appId: '1:900834578203:ios:8fe750179dd1dc86ebcdbe',
    messagingSenderId: '900834578203',
    projectId: 'iosnative-9791f',
    storageBucket: 'iosnative-9791f.appspot.com',
    iosClientId: '900834578203-cnrscsfb48b2m279tfkhg3n9cmhoad1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVsNative',
  );
}
